/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proiect;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author petri
 */
public class AdaugaAngajat extends javax.swing.JFrame {
    FunctiiAngajati trimite_date = new FunctiiAngajati();
    public AdaugaAngajat() {
        initComponents(); 
        id_angajat.setText(String.valueOf(trimite_date.id_utilizator_nou()));
        setVisible(true);
        setResizable(false);
        setSize(360,550);
        setTitle("Adauga angajat-Craciun Petrisor");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        id_angajat = new javax.swing.JLabel();
        text_telefon = new javax.swing.JLabel();
        text_parola = new javax.swing.JLabel();
        text_nume = new javax.swing.JLabel();
        text_prenume = new javax.swing.JLabel();
        text_adresa = new javax.swing.JLabel();
        text_email = new javax.swing.JLabel();
        buton_anuleaza = new javax.swing.JButton();
        buton_adauga = new javax.swing.JButton();
        casuta_email = new javax.swing.JTextField();
        casuta_username = new javax.swing.JTextField();
        casuta_parola = new javax.swing.JTextField();
        casuta_nume = new javax.swing.JTextField();
        casuta_adresa = new javax.swing.JTextField();
        casuta_salariu = new javax.swing.JTextField();
        casuta_prenume = new javax.swing.JTextField();
        text_username = new javax.swing.JLabel();
        text_id_angajat = new javax.swing.JLabel();
        text_telefon1 = new javax.swing.JLabel();
        text_telefon2 = new javax.swing.JLabel();
        casuta_telefon = new javax.swing.JTextField();
        text_telefon3 = new javax.swing.JLabel();
        casuta_data_angajare = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Adauga angajat");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(jLabel2)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 360, 40);

        id_angajat.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        id_angajat.setText("0");
        getContentPane().add(id_angajat);
        id_angajat.setBounds(100, 50, 117, 19);

        text_telefon.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        text_telefon.setText("angajare:");
        getContentPane().add(text_telefon);
        text_telefon.setBounds(20, 380, 117, 19);

        text_parola.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        text_parola.setText("Parola:");
        getContentPane().add(text_parola);
        text_parola.setBounds(10, 120, 117, 19);

        text_nume.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        text_nume.setText("Nume:");
        getContentPane().add(text_nume);
        text_nume.setBounds(10, 160, 117, 19);

        text_prenume.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        text_prenume.setText("Prenume:");
        getContentPane().add(text_prenume);
        text_prenume.setBounds(10, 200, 117, 19);

        text_adresa.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        text_adresa.setText("Adresa:");
        getContentPane().add(text_adresa);
        text_adresa.setBounds(10, 240, 117, 19);

        text_email.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        text_email.setText("Email:");
        getContentPane().add(text_email);
        text_email.setBounds(10, 280, 117, 19);

        buton_anuleaza.setIcon(new javax.swing.ImageIcon("C:\\Users\\petri\\Desktop\\Practica2018\\imagini\\anuleaza.png")); // NOI18N
        buton_anuleaza.setText("Anuleaza");
        getContentPane().add(buton_anuleaza);
        buton_anuleaza.setBounds(200, 460, 120, 40);

        buton_adauga.setIcon(new javax.swing.ImageIcon("C:\\Users\\petri\\Desktop\\Practica2018\\imagini\\adauga.png")); // NOI18N
        buton_adauga.setText("Adauga angajat");
        buton_adauga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buton_adaugaMouseClicked(evt);
            }
        });
        getContentPane().add(buton_adauga);
        buton_adauga.setBounds(20, 460, 150, 40);
        getContentPane().add(casuta_email);
        casuta_email.setBounds(100, 280, 210, 30);
        getContentPane().add(casuta_username);
        casuta_username.setBounds(100, 80, 210, 30);
        getContentPane().add(casuta_parola);
        casuta_parola.setBounds(100, 120, 210, 30);
        getContentPane().add(casuta_nume);
        casuta_nume.setBounds(100, 160, 210, 30);
        getContentPane().add(casuta_adresa);
        casuta_adresa.setBounds(100, 240, 210, 30);
        getContentPane().add(casuta_salariu);
        casuta_salariu.setBounds(100, 410, 210, 30);
        getContentPane().add(casuta_prenume);
        casuta_prenume.setBounds(100, 200, 210, 30);

        text_username.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        text_username.setText("Username:");
        getContentPane().add(text_username);
        text_username.setBounds(10, 80, 117, 19);

        text_id_angajat.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        text_id_angajat.setText("ID angajat:");
        getContentPane().add(text_id_angajat);
        text_id_angajat.setBounds(10, 50, 117, 19);

        text_telefon1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        text_telefon1.setText("Telefon:");
        getContentPane().add(text_telefon1);
        text_telefon1.setBounds(10, 320, 117, 19);

        text_telefon2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        text_telefon2.setText("Salariu:");
        getContentPane().add(text_telefon2);
        text_telefon2.setBounds(10, 420, 117, 19);
        getContentPane().add(casuta_telefon);
        casuta_telefon.setBounds(100, 320, 210, 30);

        text_telefon3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        text_telefon3.setText("Data ");
        getContentPane().add(text_telefon3);
        text_telefon3.setBounds(10, 360, 117, 19);
        getContentPane().add(casuta_data_angajare);
        casuta_data_angajare.setBounds(100, 370, 210, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buton_adaugaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buton_adaugaMouseClicked
        String[] date = new String[10];
        date[1]=casuta_username.getText();
        date[2]=casuta_parola.getText();
        date[3]=casuta_nume.getText();
        date[4]=casuta_prenume.getText();
        date[5]=casuta_adresa.getText();
        date[6]=casuta_email.getText();
        date[7]=casuta_telefon.getText();
        date[8]=casuta_data_angajare.getText();
        date[9]=casuta_salariu.getText();
        
        JFrame f = new JFrame(); 
        if(trimite_date.AdaugaCont(date)==1)
        {
             JOptionPane.showMessageDialog(f,"Datele au fost adaugate cu sucees.");
             dispose();          
        }
        else
        {
            JOptionPane.showMessageDialog(f,"Au aparut probleme la adaugarea datelor.");
        }
    }//GEN-LAST:event_buton_adaugaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdaugaAngajat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdaugaAngajat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdaugaAngajat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdaugaAngajat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdaugaAngajat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buton_adauga;
    private javax.swing.JButton buton_anuleaza;
    private javax.swing.JTextField casuta_adresa;
    private javax.swing.JTextField casuta_data_angajare;
    private javax.swing.JTextField casuta_email;
    private javax.swing.JTextField casuta_nume;
    private javax.swing.JTextField casuta_parola;
    private javax.swing.JTextField casuta_prenume;
    private javax.swing.JTextField casuta_salariu;
    private javax.swing.JTextField casuta_telefon;
    private javax.swing.JTextField casuta_username;
    private javax.swing.JLabel id_angajat;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel text_adresa;
    private javax.swing.JLabel text_email;
    private javax.swing.JLabel text_id_angajat;
    private javax.swing.JLabel text_nume;
    private javax.swing.JLabel text_parola;
    private javax.swing.JLabel text_prenume;
    private javax.swing.JLabel text_telefon;
    private javax.swing.JLabel text_telefon1;
    private javax.swing.JLabel text_telefon2;
    private javax.swing.JLabel text_telefon3;
    private javax.swing.JLabel text_username;
    // End of variables declaration//GEN-END:variables
}
