/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proiect;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.border.EmptyBorder;

/**
 *
 * @author petri
 */
public class PaginaLogin extends javax.swing.JFrame {

    FunctiiAngajati Functii_Angajati = new FunctiiAngajati();
    public PaginaLogin() {
        initComponents();
        
        setVisible(true);
        setSize(1000,550);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        text_creator = new javax.swing.JLabel();
        Panou1 = new javax.swing.JPanel();
        buton_logare = new javax.swing.JButton();
        parola_text = new javax.swing.JLabel();
        username_text = new javax.swing.JLabel();
        casuta_parola = new javax.swing.JPasswordField();
        casuta_username = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        fundal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Proiect practica 2018\n");
        getContentPane().setLayout(null);

        text_creator.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        text_creator.setText("Proiect realizat de Craciun Petrisor");
        getContentPane().add(text_creator);
        text_creator.setBounds(10, 430, 320, 23);

        Panou1.setBackground(new java.awt.Color(255, 204, 51));
        Panou1.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createCompoundBorder()));
        Panou1.setFocusCycleRoot(true);

        buton_logare.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        buton_logare.setText("Logare");
        buton_logare.setOpaque(false);
        buton_logare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buton_logareMouseClicked(evt);
            }
        });

        parola_text.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        parola_text.setText("Parola:");

        username_text.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        username_text.setText("Username:");

        jButton1.setText("Deschide tastatura");

        javax.swing.GroupLayout Panou1Layout = new javax.swing.GroupLayout(Panou1);
        Panou1.setLayout(Panou1Layout);
        Panou1Layout.setHorizontalGroup(
            Panou1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panou1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panou1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panou1Layout.createSequentialGroup()
                        .addGroup(Panou1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(casuta_username, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Panou1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(username_text)
                                .addGroup(Panou1Layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(casuta_parola, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(parola_text)))
                        .addGap(0, 9, Short.MAX_VALUE))
                    .addComponent(buton_logare, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panou1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        Panou1Layout.setVerticalGroup(
            Panou1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panou1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(username_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(casuta_username, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(parola_text)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(casuta_parola, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(buton_logare, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        getContentPane().add(Panou1);
        Panou1.setBounds(700, 10, 270, 440);

        fundal.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\Practica2018\\imagini\\fundal.jpg")); // NOI18N
        fundal.setOpaque(true);
        getContentPane().add(fundal);
        fundal.setBounds(0, 0, 1920, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buton_logareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buton_logareMouseClicked
        String tnume=casuta_username.getText();
        String tparola=casuta_parola.getText();
        if(tnume.equals("0000") && tparola.equals("0000"))
        {
            dispose();
            try {
                new PanouAdmin();
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(PaginaLogin.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else if(Functii_Angajati.VerificaLogin(tnume,tparola)==1)
        {
            dispose();
            new PaginaAngajat();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Datele introduse sunt gresite.");
        }
    }//GEN-LAST:event_buton_logareMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panou1;
    private javax.swing.JButton buton_logare;
    private javax.swing.JPasswordField casuta_parola;
    private javax.swing.JTextField casuta_username;
    private javax.swing.JLabel fundal;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel parola_text;
    private javax.swing.JLabel text_creator;
    private javax.swing.JLabel username_text;
    // End of variables declaration//GEN-END:variables
}
