package proiect;

import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.util.Calendar;
import javax.swing.JPanel;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.Timer;

public class PanouAdmin extends javax.swing.JFrame {
    
    public PanouAdmin() throws ClassNotFoundException {
        initComponents();
        setResizable(false);

        setResizable(false);
        setLocationRelativeTo(null);
        Calendar rightNow = Calendar.getInstance();
        String ora_actuala = rightNow.get(Calendar.HOUR_OF_DAY) + ":" + rightNow.get(Calendar.MINUTE);
        ora.setText(ora_actuala);
        String data_actuala = rightNow.get(Calendar.DAY_OF_MONTH) + "/" + (rightNow.get(Calendar.MONTH)+1) + "/" + rightNow.get(Calendar.YEAR);
        data.setText(data_actuala);
        this.setLocationRelativeTo(null);
        setVisible(true);
        setSize(950,500);
        setTitle("Craciun Petrisor");
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panou_sus = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Panou_meniu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        buton_acasa = new javax.swing.JButton();
        buton_produse = new javax.swing.JButton();
        buton_angajati = new javax.swing.JButton();
        buton_vanzari = new javax.swing.JButton();
        buton_furnizori = new javax.swing.JButton();
        buton_delogare = new javax.swing.JButton();
        Panou_centru = new javax.swing.JPanel();
        text_bunvenit = new javax.swing.JLabel();
        nume_admin = new javax.swing.JLabel();
        text_data = new javax.swing.JLabel();
        data = new javax.swing.JLabel();
        text_ora = new javax.swing.JLabel();
        ora = new javax.swing.JLabel();
        Meniu_sus = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Panou_sus.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Panou de administrator POS - Craciun Petrisor 2018");

        javax.swing.GroupLayout Panou_susLayout = new javax.swing.GroupLayout(Panou_sus);
        Panou_sus.setLayout(Panou_susLayout);
        Panou_susLayout.setHorizontalGroup(
            Panou_susLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panou_susLayout.createSequentialGroup()
                .addGap(274, 274, 274)
                .addComponent(jLabel1)
                .addContainerGap(284, Short.MAX_VALUE))
        );
        Panou_susLayout.setVerticalGroup(
            Panou_susLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panou_susLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        getContentPane().add(Panou_sus);
        Panou_sus.setBounds(0, 0, 950, 40);

        Panou_meniu.setBackground(new java.awt.Color(102, 102, 102));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Meniu:");

        buton_acasa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buton_acasaMouseClicked(evt);
            }
        });

        buton_produse.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\Proiect POS\\imagini\\produse.png")); // NOI18N
        buton_produse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buton_produseMouseClicked(evt);
            }
        });

        buton_angajati.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\Proiect POS\\imagini\\angajati.png")); // NOI18N
        buton_angajati.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buton_angajatiMouseClicked(evt);
            }
        });
        buton_angajati.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_angajatiActionPerformed(evt);
            }
        });

        buton_vanzari.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\Proiect POS\\imagini\\vanzari.png")); // NOI18N
        buton_vanzari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buton_vanzariMouseClicked(evt);
            }
        });

        buton_furnizori.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\Proiect POS\\imagini\\furnizori.png")); // NOI18N
        buton_furnizori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buton_furnizoriMouseClicked(evt);
            }
        });
        buton_furnizori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_furnizoriActionPerformed(evt);
            }
        });

        buton_delogare.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\Desktop\\Proiect POS\\imagini\\delogare.png")); // NOI18N
        buton_delogare.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buton_delogareMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panou_meniuLayout = new javax.swing.GroupLayout(Panou_meniu);
        Panou_meniu.setLayout(Panou_meniuLayout);
        Panou_meniuLayout.setHorizontalGroup(
            Panou_meniuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panou_meniuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Panou_meniuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Panou_meniuLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(buton_acasa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buton_produse, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(buton_angajati, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buton_vanzari, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buton_furnizori, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buton_delogare, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        Panou_meniuLayout.setVerticalGroup(
            Panou_meniuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panou_meniuLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buton_acasa, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buton_produse, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buton_angajati, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buton_vanzari, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buton_furnizori, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buton_delogare, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(Panou_meniu);
        Panou_meniu.setBounds(0, 50, 130, 400);

        Panou_centru.setBackground(new java.awt.Color(102, 102, 102));
        Panou_centru.setLayout(null);
        getContentPane().add(Panou_centru);
        Panou_centru.setBounds(140, 80, 800, 370);

        text_bunvenit.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        text_bunvenit.setText("Bun venit,");
        getContentPane().add(text_bunvenit);
        text_bunvenit.setBounds(140, 50, 90, 21);

        nume_admin.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        nume_admin.setText("admin");
        getContentPane().add(nume_admin);
        nume_admin.setBounds(230, 50, 140, 21);

        text_data.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        text_data.setText("Data:");
        getContentPane().add(text_data);
        text_data.setBounds(790, 50, 50, 21);

        data.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        data.setText("01/01/2018");
        getContentPane().add(data);
        data.setBounds(850, 50, 90, 21);

        text_ora.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        text_ora.setText("Ultima conectare:");
        getContentPane().add(text_ora);
        text_ora.setBounds(590, 50, 160, 21);

        ora.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        ora.setText("00:00");
        getContentPane().add(ora);
        ora.setBounds(740, 50, 40, 21);
        setJMenuBar(Meniu_sus);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buton_acasaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buton_acasaMouseClicked
        // TODO add your handling code here:
       
        
    }//GEN-LAST:event_buton_acasaMouseClicked

    private void buton_produseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buton_produseMouseClicked
       Panou_centru.removeAll();
       Panou_centru.revalidate();
       Panou_centru.repaint();
       PaginaProduse Panou_Produse = new PaginaProduse();
       Panou_centru.add(Panou_Produse);
       Panou_centru.revalidate();
       Panou_centru.repaint();
    }//GEN-LAST:event_buton_produseMouseClicked

    private void buton_angajatiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buton_angajatiMouseClicked
        // TODO add your handling code here:
       Panou_centru.removeAll();
       Panou_centru.revalidate();
       Panou_centru.repaint();
       PanouAngajati Panou_Angajati=new PanouAngajati();
       Panou_centru.add(Panou_Angajati);
       Panou_centru.revalidate();
       Panou_centru.repaint();

    }//GEN-LAST:event_buton_angajatiMouseClicked

    private void buton_furnizoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buton_furnizoriMouseClicked
        // TODO add your handling code here:
       Panou_centru.removeAll();
       Panou_centru.revalidate();
       Panou_centru.repaint();
       PanouFurnizori Panou_Furnizori = new PanouFurnizori();
       Panou_centru.add(Panou_Furnizori);
       Panou_centru.revalidate();
       Panou_centru.repaint();
    }//GEN-LAST:event_buton_furnizoriMouseClicked

    private void buton_furnizoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_furnizoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buton_furnizoriActionPerformed

    private void buton_angajatiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_angajatiActionPerformed

    }//GEN-LAST:event_buton_angajatiActionPerformed

    private void buton_vanzariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buton_vanzariMouseClicked
       Panou_centru.removeAll();
       Panou_centru.revalidate();
       Panou_centru.repaint();
       PanouVanzari Panou_Vanzari = new PanouVanzari();
       Panou_centru.add(Panou_Vanzari);
       Panou_centru.revalidate();
       Panou_centru.repaint();
    }//GEN-LAST:event_buton_vanzariMouseClicked

    private void buton_delogareMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buton_delogareMouseClicked
        dispose();
        new PaginaLogin();
    }//GEN-LAST:event_buton_delogareMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanouAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanouAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanouAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanouAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PanouAdmin().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(PanouAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Meniu_sus;
    public javax.swing.JPanel Panou_centru;
    private javax.swing.JPanel Panou_meniu;
    private javax.swing.JPanel Panou_sus;
    private javax.swing.JButton buton_acasa;
    private javax.swing.JButton buton_angajati;
    private javax.swing.JButton buton_delogare;
    private javax.swing.JButton buton_furnizori;
    private javax.swing.JButton buton_produse;
    private javax.swing.JButton buton_vanzari;
    private javax.swing.JLabel data;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel nume_admin;
    private javax.swing.JLabel ora;
    private javax.swing.JLabel text_bunvenit;
    private javax.swing.JLabel text_data;
    private javax.swing.JLabel text_ora;
    // End of variables declaration//GEN-END:variables
}
