/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proiect;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author petri
 */
public class PanouAngajati extends javax.swing.JPanel {

    FunctiiAngajati functii = new FunctiiAngajati();
    public PanouAngajati() {
        initComponents();       
        setSize(800,370);
        setVisible(true);
        tabel_angajati.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tabel_angajati.getTableHeader().setReorderingAllowed(false);
        tabel_angajati.getColumnModel().getColumn(0).setPreferredWidth(37);
        tabel_angajati.getColumnModel().getColumn(1).setPreferredWidth(130);
        tabel_angajati.getColumnModel().getColumn(2).setPreferredWidth(100);
        tabel_angajati.getColumnModel().getColumn(3).setPreferredWidth(80);
        tabel_angajati.getColumnModel().getColumn(4).setPreferredWidth(80);
        tabel_angajati.getColumnModel().getColumn(5).setPreferredWidth(100);
        tabel_angajati.getColumnModel().getColumn(6).setPreferredWidth(100);
        tabel_angajati.getColumnModel().getColumn(7).setPreferredWidth(120);
        tabel_angajati.getColumnModel().getColumn(8).setPreferredWidth(105);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panou_Angajati_centru = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_angajati = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        buton_adauga_angajat = new javax.swing.JButton();
        buton_sterge_angajat = new javax.swing.JButton();
        buton_modifica_detalii = new javax.swing.JButton();

        setLayout(null);

        Panou_Angajati_centru.setBackground(new java.awt.Color(102, 102, 102));

        tabel_angajati.setModel(functii.tabel_date_angajati());
        jScrollPane1.setViewportView(tabel_angajati);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Lista angajati:");

        buton_adauga_angajat.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        buton_adauga_angajat.setIcon(new javax.swing.ImageIcon("C:\\Users\\petri\\Desktop\\Practica2018\\imagini\\adauga.png")); // NOI18N
        buton_adauga_angajat.setText("Adauga angajat");
        buton_adauga_angajat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buton_adauga_angajatMouseClicked(evt);
            }
        });

        buton_sterge_angajat.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        buton_sterge_angajat.setIcon(new javax.swing.ImageIcon("C:\\Users\\petri\\Desktop\\Practica2018\\imagini\\sterge.png")); // NOI18N
        buton_sterge_angajat.setText("Sterge angajat");
        buton_sterge_angajat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buton_sterge_angajatMouseClicked(evt);
            }
        });

        buton_modifica_detalii.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        buton_modifica_detalii.setIcon(new javax.swing.ImageIcon("C:\\Users\\petri\\Desktop\\Practica2018\\imagini\\modifica.png")); // NOI18N
        buton_modifica_detalii.setText("Modifica detalii");
        buton_modifica_detalii.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buton_modifica_detaliiMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout Panou_Angajati_centruLayout = new javax.swing.GroupLayout(Panou_Angajati_centru);
        Panou_Angajati_centru.setLayout(Panou_Angajati_centruLayout);
        Panou_Angajati_centruLayout.setHorizontalGroup(
            Panou_Angajati_centruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panou_Angajati_centruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(681, Short.MAX_VALUE))
            .addGroup(Panou_Angajati_centruLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(buton_adauga_angajat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(buton_sterge_angajat)
                .addGap(88, 88, 88)
                .addComponent(buton_modifica_detalii)
                .addGap(70, 70, 70))
            .addGroup(Panou_Angajati_centruLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        Panou_Angajati_centruLayout.setVerticalGroup(
            Panou_Angajati_centruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panou_Angajati_centruLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(Panou_Angajati_centruLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buton_adauga_angajat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_sterge_angajat, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buton_modifica_detalii, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        add(Panou_Angajati_centru);
        Panou_Angajati_centru.setBounds(0, 0, 800, 370);
    }// </editor-fold>//GEN-END:initComponents

    private void buton_adauga_angajatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buton_adauga_angajatMouseClicked
        // TODO add your handling code here:
        new AdaugaAngajat();
    }//GEN-LAST:event_buton_adauga_angajatMouseClicked

    private void buton_modifica_detaliiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buton_modifica_detaliiMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_buton_modifica_detaliiMouseClicked

    private void buton_sterge_angajatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buton_sterge_angajatMouseClicked
        try {
                    int linieselectata=tabel_angajati.getSelectedRow();
                    if(linieselectata == -1  )
                    {
                       JOptionPane.showMessageDialog(null, "Este necesara alegerea unui rand din tabel.");
                    }
                    else 
                    {
                        int linie = Integer.parseInt(tabel_angajati.getModel().getValueAt(linieselectata,0).toString());
                        functii.StergeAngajat(linie);
                        JOptionPane.showMessageDialog(null, "Angajatul a fost sters cu succes.");
                    }
                    
                    
                } catch (Exception ex) {

                }
    }//GEN-LAST:event_buton_sterge_angajatMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Panou_Angajati_centru;
    private javax.swing.JButton buton_adauga_angajat;
    private javax.swing.JButton buton_modifica_detalii;
    private javax.swing.JButton buton_sterge_angajat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_angajati;
    // End of variables declaration//GEN-END:variables
}
